---
title: "Stats Grades Project Data Prep"
author: "Sky Taylor"
format: 
  html:
    self-contained: true
    toc: true
editor: visual
---

## Filtering

```{r, message=FALSE}
#load packages
library(dplyr)
library(readr)
library(here)
library(tidyverse)

#read in data
data <- here("data/smarvus_extra_grade_data.csv") |> read.csv()
```

```{r}
#select variables
data <- data |> 
  select(unique_id, university, starts_with("stats_edu_"), grade_module_name, emsa_grade, srm_grade, dasar_grade, inferensial_grade, ist101_grade, ist102_grade, psk202_grade, rs2_grade, rs4_grade, ams_grade, yr1_grade, stats_mcq1_L2, stats_mcq2_L2, yr2_grade)

#filter out NAs
data_filtered <- data |> 
  filter(if_any(c(stats_edu_grade_1, stats_edu_grade_2, stats_edu_grade_3, stats_edu_grade_4, stats_edu_grade_5, stats_edu_grade_6), ~ !is.na(.)) & if_any(c(emsa_grade, srm_grade, dasar_grade, inferensial_grade, ist101_grade, ist102_grade, psk202_grade, rs2_grade, rs4_grade, ams_grade, yr1_grade, stats_mcq1_L2, stats_mcq2_L2, yr2_grade), ~ !is.na(.)))
```

```{r}
write.csv(data_filtered, "filtered_grades.csv")
```

## Recoded data

```{r}
#read in data
data_recoded <- here("data/filtered_grades_coded.csv") |> read.csv()

#select variables
data_recoded <- data_recoded |> 
  select(unique_id, university, ends_with("recode"), starts_with("stats_edu_grade"), emsa_grade, srm_grade, dasar_grade, inferensial_grade, ist101_grade, ist102_grade, psk202_grade, yr1_grade, yr2_grade)
```

```{r}
#extract self report grades for each module
self_report_data <- data_recoded |> 
  mutate(
    emsa_self_report =
      case_when(
        stats_edu_module_1_recode == "EMSA" ~ stats_edu_grade_1,
        stats_edu_module_2_recode  == "EMSA" ~ stats_edu_grade_2,
        stats_edu_module_3_recode  == "EMSA" ~ stats_edu_grade_3,
        stats_edu_module_4_recode  == "EMSA" ~ stats_edu_grade_4,
        stats_edu_module_5_recode  == "EMSA" ~ stats_edu_grade_5,
        stats_edu_module_6_recode  == "EMSA" ~ stats_edu_grade_6
    ),
    srm_self_report =
      case_when(
        stats_edu_module_1_recode == "SRM" ~ stats_edu_grade_1,
        stats_edu_module_2_recode  == "SRM" ~ stats_edu_grade_2,
        stats_edu_module_3_recode  == "SRM" ~ stats_edu_grade_3,
        stats_edu_module_4_recode  == "SRM" ~ stats_edu_grade_4,
        stats_edu_module_5_recode  == "SRM" ~ stats_edu_grade_5,
        stats_edu_module_6_recode  == "SRM" ~ stats_edu_grade_6
    ),      
    dasar_self_report =
      case_when(
        stats_edu_module_1_recode == "Basic" ~ stats_edu_grade_1,
        stats_edu_module_2_recode  == "Basic" ~ stats_edu_grade_2,
        stats_edu_module_3_recode  == "Basic" ~ stats_edu_grade_3,
        stats_edu_module_4_recode  == "Basic" ~ stats_edu_grade_4,
        stats_edu_module_5_recode  == "Basic" ~ stats_edu_grade_5,
        stats_edu_module_6_recode  == "Basic" ~ stats_edu_grade_6
    ),
    inferensial_self_report =
      case_when(
        stats_edu_module_1_recode == "Inferential" ~ stats_edu_grade_1,
        stats_edu_module_2_recode  == "Inferential" ~ stats_edu_grade_2,
        stats_edu_module_3_recode  == "Inferential" ~ stats_edu_grade_3,
        stats_edu_module_4_recode  == "Inferential" ~ stats_edu_grade_4,
        stats_edu_module_5_recode  == "Inferential" ~ stats_edu_grade_5,
        stats_edu_module_6_recode  == "Inferential" ~ stats_edu_grade_6
    ),
    ist101_self_report =
      case_when(
        stats_edu_module_1_recode == "IST101" ~ stats_edu_grade_1,
        stats_edu_module_2_recode  == "IST101" ~ stats_edu_grade_2,
        stats_edu_module_3_recode  == "IST101" ~ stats_edu_grade_3,
        stats_edu_module_4_recode  == "IST101" ~ stats_edu_grade_4,
        stats_edu_module_5_recode  == "IST101" ~ stats_edu_grade_5,
        stats_edu_module_6_recode  == "IST101" ~ stats_edu_grade_6
    ),
    ist102_self_report =
      case_when(
        stats_edu_module_1_recode == "IST102" ~ stats_edu_grade_1,
        stats_edu_module_2_recode  == "IST102" ~ stats_edu_grade_2,
        stats_edu_module_3_recode  == "IST102" ~ stats_edu_grade_3,
        stats_edu_module_4_recode  == "IST102" ~ stats_edu_grade_4,
        stats_edu_module_5_recode  == "IST102" ~ stats_edu_grade_5,
        stats_edu_module_6_recode  == "IST102" ~ stats_edu_grade_6
    ),
    psk202_self_report =
      case_when(
        stats_edu_module_1_recode == "PSK202" ~ stats_edu_grade_1,
        stats_edu_module_2_recode  == "PSK202" ~ stats_edu_grade_2,
        stats_edu_module_3_recode  == "PSK202" ~ stats_edu_grade_3,
        stats_edu_module_4_recode  == "PSK202" ~ stats_edu_grade_4,
        stats_edu_module_5_recode  == "PSK202" ~ stats_edu_grade_5,
        stats_edu_module_6_recode  == "PSK202" ~ stats_edu_grade_6
    ),
    yr1_self_report =
      case_when(
        stats_edu_module_1_recode == "Year1" ~ stats_edu_grade_1,
        stats_edu_module_2_recode  == "Year1" ~ stats_edu_grade_2,
        stats_edu_module_3_recode  == "Year1" ~ stats_edu_grade_3,
        stats_edu_module_4_recode  == "Year1" ~ stats_edu_grade_4,
        stats_edu_module_5_recode  == "Year1" ~ stats_edu_grade_5,
        stats_edu_module_6_recode  == "Year1" ~ stats_edu_grade_6
    ),
    yr2_self_report =
      case_when(
        stats_edu_module_1_recode == "Year2" ~ stats_edu_grade_1,
        stats_edu_module_2_recode  == "Year2" ~ stats_edu_grade_2,
        stats_edu_module_3_recode  == "Year2" ~ stats_edu_grade_3,
        stats_edu_module_4_recode  == "Year2" ~ stats_edu_grade_4,
        stats_edu_module_5_recode  == "Year2" ~ stats_edu_grade_5,
        stats_edu_module_6_recode  == "Year2" ~ stats_edu_grade_6
    )
  )

#select variables
self_report_data <- self_report_data |> 
  select(unique_id, ends_with("grade"), ends_with("report"))
```

## Sussex data

```{r}
#read in data
data_sussex <- here("data/sussex_extra_grade_data.csv") |> read.csv()

#filter out non-participants
data_sussex <- data_sussex |> 
  filter(!is.na(unique_id))

#conver to numbers
data_sussex <- data_sussex |> 
mutate(
  across(2:7, ~ as.numeric(parse_number(.x)))
)

#combine modules across different years
data_sussex <- data_sussex |> 
  mutate( 
    paas_grade = case_when(
      !is.na(pass_2019) & is.na(paas_2020) ~ pass_2019,
      is.na(pass_2019) & !is.na(paas_2020) ~ paas_2020,
      !is.na(pass_2019) & !is.na(paas_2020) ~ NA
    ),
    ds_grade = case_when(
      !is.na(ds_2019) & is.na(ds_2020) ~ ds_2019,
      is.na(ds_2019) & !is.na(ds_2020) ~ ds_2020,
      !is.na(ds_2019) & !is.na(ds_2020) ~ NA
    ),
    qqm_grade = qqm_2019,
    ad_grade = and_2019) |> 
      select(unique_id, paas_grade, ad_grade, ds_grade, qqm_grade) 
```

```{r}
#read in smarvus
smarvus <- here("data/smarvus_complete_250124_st.csv") |> read.csv()

#select sussex self-reported grades
sussex_self_report <- smarvus |> 
  filter(university == "University of Sussex") |> 
    mutate(
        paas_self_report = as.numeric(stats_edu_grade_1_edited),
        ad_self_report = as.numeric(stats_edu_grade_2_edited),
        ds_self_report = as.numeric(stats_edu_grade_3_edited),
        qqm_self_report = as.numeric(stats_edu_grade_4_edited)) |> 
  select(unique_id, paas_self_report, ad_self_report, ds_self_report, qqm_self_report)
```

## Final dataset

```{r}
#join data to smarvus
complete_data <- smarvus |> 
  left_join(data_sussex, by = "unique_id") |> 
  left_join(self_report_data, by = "unique_id") |> 
  left_join(sussex_self_report, by = "unique_id")

#write to csv
write.csv(complete_data, "smarvus_self_report.csv")
```
